# -*- coding: utf-8 -*-
"""ARMA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svJI9Cgso1P1YG6lDb8UYTsy2_uM3dQ5
"""

# ! pip install statsmodels --upgrade

# Basic Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
from copy import deepcopy
# plt.style.use('seaborn')
# warnings
import warnings 
warnings.filterwarnings('ignore')
# algotihms
from statsmodels.tsa.api import ExponentialSmoothing, SimpleExpSmoothing, Holt
from statsmodels.tsa.arima.model import ARIMA
# from statsmodels.tsa.arima.estimators.yule_walker import yule_walker
# from statsmodels.tsa.arima.estimators.burg import burg
# from statsmodels.tsa.arima.estimators.hannan_rissanen import hannan_rissanen
# from statsmodels.tsa.arima.estimators.innovations import (innovations, innovations_mle)

class ModelSelection:
    def __init__(self, Data, pMax=5, qMax=5):
        self.data = Data
        self.p = pMax
        self.q = qMax

    def getICseries(self):
        aicc=[]
        for i in range(self.p):
            for j in range(self.q):
                try:
                    aic = ARIMA(self.data, order=(i, 0, j)).fit().aic
                    bic = ARIMA(self.data, order=(i, 0, j)).fit().bic
                    aicc.append([i, j, aic, bic])
                except:
                    continue
        df = pd.DataFrame(aicc, columns=['p', 'q', 'AIC', 'BIC'])
        return df

class AR:
    def __init__(self, Data, p = 1, method='Burg', trend='ct'):
        self.data = Data
        self.p = p
        self.trend = trend
        self.method = method
        self.model = ARIMA(self.data, order = (self.p, 0, 0), trend=self.trend)
        if method is 'YW':
            self.model = self.model.fit(method='yule_walker')
        elif method is 'Burg':
            self.model = self.model.fit(method='burg')
        else:
            self.model = self.model.fit()
        
    def getParams(self):
        names = self.model.param_names
        param = self.model.params.values
        pvalue = self.model.pvalues
        tstat = self.model.tvalues
        std = self.model.bse
        res = pd.DataFrame([names, param, tstat, pvalue, std],
                           index=['Name', 'Coefficient', 'Tstat', 'P-value', 'Std. Error']).T
        return res.set_index('Name')

        # coef = self.model.params.values[1:-1]
        # cons = self.model.params.values[0]
        # resid = np.sqrt(self.model.params.values[-1])
        # sigma = np.sqrt(np.mean(resid**2))x
        # param[-1] = np.std(param[-1], ddof=1)

class MA:
    def __init__(self, Data, q = 1, method='Innovation', trend='ct'):
        self.data = Data
        self.q = q
        self.trend = trend
        self.method = method
        self.model = ARIMA(self.data, order = (0, 0, self.q), trend= self.trend)
        if method is 'Innovation':
            self.model = self.model.fit(method='innovations')
        else:
            self.model = self.model.fit()
        
    def getParams(self):
        names = self.model.param_names
        param = self.model.params.values
        pvalue = self.model.pvalues
        tstat = self.model.tvalues
        std = self.model.bse
        res = pd.DataFrame([names, param, tstat, pvalue, std],
                           index=['Name', 'Coefficient', 'Tstat', 'P-value', 'Std. Error']).T
        return res.set_index('Name')

class ARMA:
    def __init__(self, Data, p = 1, q=1, method = 'HR', trend='ct'):
        self.data = Data
        self.p = p
        self.q = q
        self.trend = trend
        self.method = method
        self.model = ARIMA(self.data, order = (self.p, 0, self.q), trend=self.trend)
        if method is 'HR':
            try:
                self.model = self.model.fit(method='hannan_rissanen')
            except:
                self.model = self.model.fit()
        else:
            self.model = self.model.fit()
    
    def getModel(self):
        return self.model

    def getParams(self):
        names = self.model.param_names
        param = self.model.params.values
        pvalue = self.model.pvalues
        tstat = self.model.tvalues
        std = self.model.bse
        res = pd.DataFrame([names, param, tstat, pvalue, std],
                           index=['Name', 'Coefficient', 'Tstat', 'P-value', 'Std. Error']).T
        return res.set_index('Name')

class Model:
    def __init__(self, Data, method='CE', p=None, d=0, q=None, trend='ct'):
        self.data = Data
        self.p = p
        # d must be zero for every modelling
        self.d = d
        self.q = q
        self.trend = trend
        if self.p is None and self.q is None:
            raise ValueError("Specify p or q, both can't be None")
        self.method= method

        if self.d is not 0:
            self.data = self.data.diff()[1:]
            print('ARIMA d={}'.format(self.d))
    
    def getParams(self):
        method = self.method
        if self.q is None:
            if method is 'YW':
                mod = AR(self.data, p=self.p, method ='YW', trend=self.trend)
                params = mod.getParams()
            elif method is 'Burg':
                mod = AR(self.data, p=self.p, method ='Burg', trend=self.trend)
                params = mod.getParams()
            else:
                mod = AR(self.data, p=self.p, method ='CE', trend=self.trend)
                params = mod.getParams()

        elif self.p is None:
            if method is 'Innovation':
                mod = MA(self.data, q=self.q, method ='Innovation', trend=self.trend)
                params = mod.getParams()
            else:
                mod = MA(self.data, q=self.q, method ='CE', trend=self.trend)
                params = mod.getParams()
        
        else:
            try:
                mod = ARMA(self.data, p=self.p, q=self.q, method ='HR', trend=self.trend)
                params = mod.getParams()
            except:
                mod = ARMA(self.data, p=self.p, q=self.q, method ='CE', trend=self.trend)
                params = mod.getParams()
        self.model = mod.model
        return params

# class SimulateFD:
#     def __init__(self, model, Data=None, init_Val=None, nSim=22, nRep=20):
#         if Data is None and init_Val is None:
#             raise ValueError("Both Data and init_Val can't simulataneously be None")
#         self.data = Data
#         self.model = model
#         self.sim= nSim
#         self.rep = nRep
#         if init_Val is not None:
#             self.init = init_Val
#             if len(self.init) !=self.model.p:
#                 raise ValueError('length of init must be {}', str(self.model.p))
#         else:
#             self.init= self.data[: self.model.p].values.flatten()
#         self.param = model.model.params
#         if self.model.p is None:
#             self.beta = None
#             self.alpha = self.param[-self.model.p-self.model.q: -self.model.q].values
#         elif self.model.vol is 'GARCH':
#             self.beta = self.param[-self.model.q:].values
#         e = []
#         for i in range(self.rep):
#             e.append(np.random.randn(self.sim))
#         self.e = e
        
#     def predict(self, coef, history):
#         yhat = 0
#         coef = np.array(coef)
#         for i in range(len(coef)):
#             yhat+=coef[i]*history[-i-1]
#         return yhat

#     def getValues(self):
#         prediction = []
#         for j in range(self.rep):
#             pred = list(self.init)
#             ej = self.e[j]
#             eps = np.convolve(pred, ej**2, mode='valid')
#             for i in range(self.sim):
#                 if self.beta is not None:
#                     pred.append(self.param['omega'] + self.predict(self.beta, pred) + self.predict(self.alpha, eps[:i+self.alpha.shape[0]]))
#                 else: 
#                     pred.append(self.param['omega'] +self.predict(self.alpha, eps[:i+self.alpha.shape[0]]))
#             prediction.append(pred)
#         var = pd.DataFrame(prediction).T
#         if self.data is not None:
#             var['index'] = self.data.index[:self.sim+self.init.shape[0]]
#             var = var.set_index('index')
#         return var
    
#     def plot(self, Axes=None):
#         df = self.getValues()
#         if Axes is None:
#             fig, ax = plt.subplots(1, figsize=(24,6))
#         else:
#             ax = Axes
#         df.plot(ax=ax, color='r', alpha=0.3)
#         if self.data is not None:
#             self.data[:self.sim+self.init.shape[0]].plot(ax=ax, color='k')
#         ax.get_legend().remove()

class SimulateFD:
    def __init__(self, fittedClass, Data=None, init_Val=None, nSim=22, repetition = 30):#, fraction=0.5, fLag = 14, tolerance=1e-4):
        if Data is None and init_Val is None:
            raise ValueError("Both Data and init_Val can't simulataneously be None")
        self.data = Data
        self.model = fittedClass.model
        self.nsim = nSim
        self.rep = repetition
        if init_Val is not None:
            self.init = init_Val
        else:
            self.init = self.data.iloc[0]
        # self.frac = fraction
        # self.lag = fLag
        # self.tol = tolerance
        # self.fr =  tsa.FractionalDifferencing(numLag=self.lag, fraction=self.frac, tolerance=self.tol).getDifferencedSeries(np.log(self.data))

    def getFDValues(self):
        # copying the model to add new params
        new=deepcopy(self.model)
        
        # applying it in new disjoint dataset 
        if self.data is not None:
            # initialise the start parameter
            new.params['const'] = self.fr.iloc[0]
            predModel= new.apply(self.fr)
            # Simulation for then prediction using model class equation
            sim=predModel.simulate(nsimulations=self.nsim, repetitions=self.rep)
            sim['Date'] = self.data[self.lag:][:self.nsim].index
            sim = sim.set_index('Date')
            # getting the backoperation results
            # x =[]
            # for i in range(self.rep):
                # x.append(tsa.BackOperation(self.data.values.flatten(), sim.iloc[:, i], fraction=self.frac).getPrediction().values.flatten())
            # plotting it 
            # df=pd.DataFrame(x, columns=self.data[:self.nsim+self.lag].index).T
            return sim#, df
        else:
            new.params['const'] = self.init
            sim = new.simulate(nsimulations=self.nsim, repetitions=self.rep)
            return sim
        

    def plotFD(self, Axes=None):
        if self.data is not None:
            sim = self.getFDValues()
            # df = self.getFDValues()[1]
            if Axes is None:
                fig, ax = plt.subplots(1, figsize=(24,6))
            else:
                ax = Axes
            # df.plot(ax=ax1, color='r', alpha=0.3)
            # self.data[:self.nsim+self.lag].plot(ax=ax1, color='k')
            # ax1.get_legend().remove() 
            
            ax.plot(sim.index, self.fr[:self.nsim].values, color='k')
            sim.plot(ax=ax, color='r', alpha=0.3)
            ax.get_legend().remove()
        else:
            sim = self.getFDValues()
            if Axes is None:
                fig, ax = plt.subplots(1, figsize=(24,6))
            else:
                ax = Axes
            # ax.plot(sim.index, self.fr[:self.nsim].values, color='k')
            sim.plot(ax=ax, color='r', alpha=0.3)
            ax.get_legend().remove()