# -*- coding: utf-8 -*-
"""GARCH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZ0KfW6LId_vrGF_mn5QyOu4rr7CY7Re
"""

# ! pip install arch

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#plt.style.use('seaborn')
import arch

import warnings 
warnings.filterwarnings('ignore')

class Volatility:
    def __init__(self, p=0, q=None):
        self.p = p
        self.q = q
        self.cls = arch.univariate
    
    def getConstant(self):
        vol = self.cls.ConstantVariance()
        return vol

    def getARCH(self):
        vol = self.cls.ARCH(p=self.p)
        return vol
        
    def getGARCH(self):
        # garch specific parameter
        asym = 0
        power = 2
        # garch object
        vol = self.cls.GARCH(p=self.p, q=self.q, power=power, o=asym)
        return vol
    
    def getEGARCH(self):
        # Egarch specific parameter
        asym = 0
        # Egarch object
        vol = self.cls.EGARCH(p=self.p, q=self.q, o=asym)
        return vol
    
    def getFIGARCH(self, trunc=1000):
        # Figarch sepecific parameter
        power=2
        # Figarch object
        vol = self.cls.FIGARCH(p=self.p, q=self.q, power=power, truncation=trunc)
        return vol

class Distribution:
    def __init__(self):
        self.cls = arch.univariate
    
    def getNormal(self):
        dist = self.cls.Normal()
        return dist
    
    def getT(self):
        dist = self.cls.StudentsT()
        return dist

class Mean: 
    def __init__(self, Data, hold = 0, lags=1):
        self.data = Data
        self.cls = arch.univariate
        self.hold = hold
        self.lag = lags

    def getZeroMean(self):
        mean = self.cls.ZeroMean(self.data, hold_back = self.hold)
        return mean

    def getConstantMean(self):
        mean = self.cls.ConstantMean(self.data, hold_back =self.hold)
        return mean

    def getAR(self, constant=True):
        mean = self.cls.ARX(self.data, lags=self.lag, hold_back = self.hold, constant = constant)
        return mean

class Model:
    def __init__(self, Data , mean = 'Constant', hold = 0, vol = 'ARCH', p=1, q=None, dist = 'Normal', lags = 1, consAR=True, truncation=1000):
        self.data = Data
        self.hold = hold
        self.mean = mean
        self.vol = vol
        self.dist = dist
        self.cons = consAR
        self.p = p
        self.q = q
        self.trunc = truncation
        self.lag = lags

        # Calculating mean
        if self.mean is 'Constant':
            model = Mean(self.data, hold = self.hold).getConstantMean()
        elif self.mean is 'Zero':
            model = Mean(self.data, hold = self.hold).getZeroMean()
        elif self.mean is 'AR':
            model = Mean(self.data, hold = self.hold, lags=self.lag).getAR(constant= self.cons)
        else:
            raise TypeError('Choose among ("Constant", "Zero", "AR")!')



        # Calculating volatility
        if self.vol is 'Constant':
            model.volatility = Volatility().getConstant()
        elif self.vol is 'ARCH':
            model.volatility = Volatility(p=self.p).getARCH()
        elif self.vol is 'GARCH':
            # q (number of lags on which vol depends) must be present 
            if self.q is None:
                raise ValueError('Choose q!')
            model.volatility = Volatility(p=self.p, q=self.q).getGARCH()    
        elif self.vol is 'EGARCH':
            # q (number of lags on which vol depends) must be present 
            if self.q is None:
                raise ValueError('Choose q!')
            model.volatility = Volatility(p=self.p, q=self.q).getEGARCH()
        elif self.vol is 'FIGARCH':
            # q (number of lags on which vol depends) must be present 
            if self.q is None:
                raise ValueError('Choose q!')
            model.volatility = Volatility(p=self.p, q=self.q).getFIGARCH(trunc= self.trunc)
        else:
            raise TypeError('Choose among ("Constant","ARCH", "GARCH", "EGARCH", "FIGARCH")!')


        # Specifying Distribution of residuals
        if self.dist is 'Normal':
            model.distribution = Distribution().getNormal()
        elif self.dist is 'StudentsT':
            model.distribution = Distribution().getT()
        else:
            raise TypeError('Choose among ("Normal" , "StudentsT")!')

        # Model fitting
        self.model = model.fit(disp='off')

    def getParameters(self):
        param = self.model.params
        tstat = self.model.tvalues
        pvalue = self.model.pvalues
        std = self.model.std_err
        res = pd.DataFrame([param, tstat, pvalue, std]).T
        return res
    
    def getStatistics(self):
        aic = self.model.aic
        bic = self.model.bic
        r2 = self.model.rsquared
        scale = self.model.scale
        llk = self.model.loglikelihood

        res = pd.Series([aic, bic, r2, scale, llk], index=['aic', 'bic', 'r2', 'scale', 'loglikelihood'])
        return res
    
    def getVolatilityValues(self):
        mod = self.model
        cond = mod.conditional_volatility
        std_res = mod.std_resid
        resid = mod.resid

        res = pd.DataFrame([cond, resid, std_res]).T
        return res

class SimulateVariance:
    def __init__(self, model, Data=None, init_Val=None, nSim=22, nRep=30):
        if Data is None and init_Val is None:
            raise ValueError("Both Data and init_Val can't simulataneously be None")
        self.data = Data
        self.model = model
        self.sim= nSim
        self.rep = nRep
        if init_Val is not None:
            self.init = init_Val
            if len(self.init) !=self.model.p:
                raise ValueError('length of init must be {}', str(self.model.p))
        else:
            self.init= self.data[: self.model.p].values.flatten()
        self.param = model.model.params
        self.alpha = self.param[-self.model.p-self.model.q: -self.model.q].values
        if self.model.vol is 'ARCH':
            self.beta = None
        elif self.model.vol is 'GARCH':
            self.beta = self.param[-self.model.q:].values
        e = []
        for i in range(self.rep):
            e.append(np.random.randn(self.sim))
        self.e = e
        
    def predict(self, coef, history):
        yhat = 0
        coef = np.array(coef)
        for i in range(len(coef)):
            yhat+=coef[i]*history[-i-1]
        return yhat

    def getValues(self):
        prediction = []
        for j in range(self.rep):
            pred = list(self.init)
            ej = self.e[j]
            eps = np.convolve(pred, ej**2, mode='valid')
            for i in range(self.sim):
                if self.beta is not None:
                    pred.append(self.param['omega'] + self.predict(self.beta, pred) + self.predict(self.alpha, eps[:i+self.alpha.shape[0]]))
                else: 
                    pred.append(self.param['omega'] +self.predict(self.alpha, eps[:i+self.alpha.shape[0]]))
            prediction.append(pred)
        var = pd.DataFrame(prediction).T
        if self.data is not None:
            var['index'] = self.data.index[:self.sim+self.init.shape[0]]
            var = var.set_index('index')
        return var
    
    def plot(self, Axes=None):
        df = self.getValues()
        if Axes is None:
            fig, ax = plt.subplots(1, figsize=(24,6))
        else:
            ax = Axes
        df.plot(ax=ax, color='r', alpha=0.3)
        if self.data is not None:
            self.data[:self.sim+self.init.shape[0]].plot(ax=ax, color='k')
        ax.get_legend().remove()