# -*- coding: utf-8 -*-
"""GMM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OxDWvvr0Ov7uP5rabCy2GTfrMX8vQkvF
"""



# Basic Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns

plt.style.use('seaborn')

from sklearn.mixture import GaussianMixture
from scipy.stats import kstest, ks_2samp
import scipy.stats as stats

class EstimateParameters:

    def __init__(self, Data, Weights):
        # expected 1-D data
        self.data = np.asarray(Data)
        self.weight = np.asarray(Weights)
        # sum of the weights
        self.wsum = np.sum(self.weight)

    def getWeightedMean(self):
        # weighted mean
        Wmean = np.sum(self.weight * self.data) / self.wsum
        return Wmean

    def getWeightedSD(self):
        mean=self.getWeightedMean()
        # weighted variance
        Wvar = np.sum(self.weight * (self.data - mean)**2 ) / self.wsum
        # volatility
        Wstd = np.sqrt(Wvar)
        return Wstd

class NormalDist:

    def __init__(self, Data, mu=None, sigma=None):
        # 1-D data
        self.data = Data
        self.mean= mu
        self.std = sigma
        self.len = self.data.shape[0]

        if self.mean is None:
            # if mean of regime is not given
            self.mean = self.data.mean()
         
        if self.std is None:
            # if std of regime is not given
            self.std = self.data.std()

        # getting the range
        self.min = self.data.min()
        self.max = self.data.max()

    def genNormPDF(self):
        # define the datapoints
        x=np.linspace(self.min, self.max, self.len)
        # gaussian probability distribution 
        y = stats.norm.pdf(x, self.mean, self.std)
        
        df = pd.DataFrame(y, columns=['PDF'])
        df['x'] = x
        return df.set_index('x')

    def genNormCDF(self):
        # define the datapoints
        x=np.linspace(self.min, self.max, self.len)
        # gaussian cumulative distribution 
        y = stats.norm.cdf(x, self.mean, self.std)
        df = pd.DataFrame(y, columns=['CDF'])
        df['x'] = x
        return df.set_index('x')

    def getDensity(self):
        # probability distribution function
        pdf = stats.norm.pdf(self.data, loc=self.mean, scale=self.std)
        return pdf

    def getLogDensity(self):
        # log probability distribution function
        log_pdf = stats.norm.logpdf(self.data, loc = self.mean, scale =self.std)
        return log_pdf

    def estimateParameters(self, weights):
        esp = EstimateParameters(self.data, weights)
        self.mean= esp.getWeightedMean()
        self.std = esp.getWeightedSD()

class KStest:

    def __init__(self, A, B=None, confidence=0.95):
        self.A = np.array(A).reshape(-1)
        self.B = B
        if self.B is not None:
            self.B = np.array(B).reshape(-1)

        self.alpha = 1- confidence
    
    def getDistParam(self, data):
        # mean calculation
        mean=data.mean()
        # standard deviation
        std = data.std()
        return mean, std
        
    def getGaussianKSstats(self):
        # calculating the kolmogrov-smirnov statistics
        ks, p = kstest(self.A, 'norm', args=self.getDistParam(self.A))
        return ks, p

    def getKSstats(self):
        if self.B is None:
            # if B is not given then compare A with Normal
            print('B not given!!')
            return self.getGaussianKSstats()
        # calculating 2-sample ks-stats
        ks, p = ks_2samp(self.A, self.B)
        return ks, p 

    def checkDistribution(self):
        # checking whether they are from same distribution or not
        if self.B is None:
            return self.getGaussianKSstats()[1] < self.alpha
        else:
            return self.getKSstats()[1] < self.alpha

    def plot(self, Axes=None):
        # parameters of normal distribution
        df= NormalDist(self.A).genNormCDF()

        if (Axes is None):
            plt.figure(figsize=(12,6))
            ax = plt.gca()
        else:
            ax=Axes

        # plotting
        sns.kdeplot(self.A, cumulative =True, ax = ax, legend=True, label='Actual')        
        if self.B  is not None:
            # plot the given distribution
            sns.kdeplot(self.B, cumulative=True, ax=ax, legend=True, label='Actual')
        else:
            # plot cumulative normal distribution
            ax.plot(df.index, df.values, label='fitted normal')

class GMM:
    
    def __init__(self, Data, component=1, iteration=100, state=0):
        self.data = Data
        self.n = component
        self.iter = iteration
        self.state= state
        # make an object of GMM to use further
        self.gmm = GaussianMixture(n_components=self.n, max_iter=self.iter, random_state=self.state)
        self.gmm.fit(self.data)
        
    def getPrediction(self):
        # prediction of components
        preds = self.gmm.predict(self.data)
        predsProb = self.gmm.predict_proba(self.data)
        return [pd.Series(preds), predsProb]

    def getAttribute(self):
        mean = self.gmm.means_.flatten()
        covariance = self.gmm.covariances_.flatten()
        weights = self.gmm.weights_
        n_iter = self.gmm.n_iter_
        conv = self.gmm.converged_
        precision=self.gmm.precisions_.flatten()
        
        if conv == False:
            print('No. of iterations', n_iter)
            print('Converge', conv)
        at = pd.DataFrame([mean, covariance, weights, precision],
                        index=['mean', 'covariance', 'weights', 'precision matrix'])
        return at.T
    
    
    def getOutput(self, predSrList, meanSr, days = 65):
        
        predSr = predSrList[0]
        # predictProbaDf = pd.DataFrame(predSrList[1]).iloc[-days :]
        
        # if sign == 'POS':
        #     diff = meanSr[1] - meanSr[0]
        
        # else:
        #     diff = meanSr[0] - meanSr[1]

        # if diff > 0:       
        #     newPredSr = predSr
        
        # elif diff < 0:
        #     print('Mean was opposite')
        #     newPredSr = (predSr - 1)*-1
        
        oldValueList = list(meanSr.index.values)
        newValueList = list(meanSr.sort_values().index.values)
        newIndexList = []
        [newIndexList.append(tmpIndex) for tmpIndex in range(0, len(newValueList))]
        
        predictProbaDf = pd.DataFrame(predSrList[1],columns = newValueList).iloc[-days :]
        
        sumProbSr = predictProbaDf.sum()
        # incSumProbSr = 
        
        # print(oldValueList)
        # print(newValueList)
        
        if len(meanSr.index) == 2:
            newPredSr = predSr.replace(newValueList, newIndexList)
        elif len(meanSr.index) == 3:
            # newPredSr = predSr.replace(oldValueList, newValueList) - 1
            newPredSr = predSr.replace(newValueList, newIndexList)
            
        # print(newPredSr)
        
        weightedProbDf = newValueList*predictProbaDf
        weightedProbSr = weightedProbDf.sum(1)
        
        # print(meanSr)
        # print(newValueList)
        # print(newIndexList)
        # print(predictProbaDf)
        # print(weightedProbDf)
        # print(weightedProbDf.sum(1))
        # print(weightedProbDf.sum(1).sum())
        
        # daysPredSr = []
        # weightedPredSr = []
        
        daysPredSr = newPredSr.iloc[-days : ]
        indexSr = []
        [indexSr.append(x) for x in range(1,days+1)]
        # indexPlusOne = newPredSr.index.values + 1
        weightedPredSr = (daysPredSr * indexSr) / np.sum(indexSr)
        
        incWeightedProbSr = (weightedProbSr * indexSr) / np.sum(indexSr)
        
        
        
        return [daysPredSr, weightedPredSr, newPredSr, weightedProbSr, incWeightedProbSr]
        
        
        
    
    def plot(self, Axes=None):

        at = self.getAttribute()
        mean = at.loc[:, 'mean'].values.flatten()
        covariance = at.loc[:,'covariance'].values.flatten()
        weights = at.loc[:,'weights'].values.flatten()

        if (Axes==None):
            plt.figure(figsize=(12, 6))
            ax = plt.gca()
        else:
            ax=Axes
        agg = []
        for i in range(len(mean)):
            pdf = weights[i]*NormalDist(self.data, mu=mean[i], sigma=np.sqrt(covariance[i])).genNormPDF()
            #pdf.plot(ax=ax)
            agg.append(pdf)
            ax.plot(pdf, label=f'Gaussian{i}')
        if self.n != 1:
            ax.plot(pdf.index, np.sum(np.array(agg), axis=0), label=f'{"Aggregated"}', lw=2)
        sns.distplot(self.data, kde_kws=dict(lw=3, label='KDE'), hist_kws=dict(alpha=0.4),ax=ax, label=f'{"Normal"}')
        ax.legend()

class MMCompSelection:

    def __init__(self, Data, iteration=100, maxComp=10, state=0):
        self.data = Data
        self.iter = iteration
        self.state =state
        self.comp = maxComp

    def getIC(self):
        aic=[]
        bic=[]
        # GridSearch
        for i in range(1, self.comp):
            gmm = GMM(self.data, component=i, iteration=self.iter, state=self.state)
            # AIC
            aic.append(gmm.gmm.aic(gmm.data))
            # BIC
            bic.append(gmm.gmm.bic(gmm.data))
        # Dataframe
        df = pd.DataFrame(aic, columns=['AIC'])
        df['BIC'] = bic
        df['index'] = np.arange(1, self.comp)
        return df.set_index('index')

    def getBestComp(self):
        df = self.getIC()
        # getting
        bestA=df.loc[:, 'AIC'].idxmin()
        bestB=df.loc[:, 'BIC'].idxmin()
        return bestA, bestB

    def plotIC(self, Axes=None):
        # getting values
        ic = self.getIC()
        #setting up the axes
        if (Axes is None):
            plt.figure(figsize=(12,6))
            ax = plt.gca()
        else:
            # given axes
            ax=Axes

        ic.plot(ax=ax)

class EM:

    def __init__(self, Data, InitMean, InitStd, InitProb=None, components=None, maxIteration=1000, tolerance = 1e-5):
        # converting into 1-D data
        self.data = np.asarray(Data).flatten()
        # n
        self.len = self.data.shape[0]
        self.maxiter = maxIteration
        # m
        self.comp = components
        if self.comp is None:
            self.comp = InitMean.shape[0]
        self.tol = tolerance
        # random guess for initial mean and std
        self.mean0 = InitMean
        self.std0 =  InitStd
        if (InitProb is None):
            # equal probability 
            self.prob0 = np.array([1/self.comp]*self.comp)
        else:
            self.prob0 = InitProb

        # distribution object
        self.dist = [NormalDist(self.data, mu=self.mean0[i], sigma=self.std0[i]) for i in range(self.comp) ]

        self.weight = np.array(self.prob0) 
        self.lastLL = np.full((self.maxiter, ), np.nan) 
        self.resp = np.empty((self.len, self.comp)) 
        self.logD = np.empty((self.len, self.comp))
        
    def runAlgorithm(self):

        distributions= self.dist
        weight = self.weight 
        last_ll = self.lastLL
        resp = self.resp
        log_density = self.logD
        
        # init counter 
        iteration = 0 
        while True:

            # E-step 
            # compute responsibilities aka weights
            for d in range(self.comp):
                log_density[:, d] = distributions[d].getLogDensity()
                
            # normalize responsibilities of distributions so they sum up to one for example
            resp = weight[np.newaxis, :] * np.exp(log_density)
            resp /= np.sum(resp, axis=1)[:, np.newaxis]
            
            # compute log-likelihood
            # matrix multiplication
            log_likelihood = np.sum(resp @ log_density.T) 
            #log_density, resp, log_likelihood = self.ExpectationStep()
            
            # M-step 
            for d in range(self.comp):
                distributions[d].estimateParameters(resp[:, d])

            weight = np.mean(resp, axis=0)
            #weight = self.MaximisationStep()
            
            # check convergence
            if np.isnan(log_likelihood):
                last_ll[0] = log_likelihood
                print('loglk is nan')
                break
            
            if  ((last_ll[0] - log_likelihood) / last_ll[0]) <= self.tol:
                last_ll[0] = log_likelihood
                print('change in loglk less than tolerance')
                break

            if iteration >= self.maxiter:
                last_ll[0] = log_likelihood
                print('reached maximum iterations')
                break

            # store value of current iteration in last_ll[0]
            #   and shift older values to the right   
            last_ll[1:] = last_ll[:-1]
            last_ll[0] = log_likelihood

            # self.logD = log_density
            # self.weight = weight
            # self.resp = resp
            
            # display     
            mus = np.array([distributions[i].mean for i in range(self.comp)])
            sigs = np.array([distributions[i].std for i in range(self.comp)])
            
            
            self.iterData = (pd.DataFrame(np.vstack([mus, sigs, weight]),
                                    index=['means', 'sigmas', 'weights']).round(4))
            
            if iteration % 50==0:
                print(f'iteration: {iteration}')
                print(f"ll new: {last_ll[0].round(4)}")
                print(self.iterData.T)
            iteration += 1  

    def ExpectationStep(self):
        distributions= self.dist
        logD = self.logD
        weight = self.weight

        # compute responsibilities aka weights
        for d in range(self.comp):
            logD[:, d] = distributions[d].getLogDensity()
            
        # normalize responsibilities of distributions so they sum up to one for example
        resp = weight[np.newaxis, :] * np.exp(logD)
        resp /= np.sum(resp, axis=1)[:, np.newaxis]
        
        # compute log-likelihood
        # matrix multiplication
        logL = np.sum(resp @ logD.T) 

        return logD, resp, logL

    def MaximisationStep(self):
        distributions= self.dist 
        resp= self.resp      
        # now that we have the new weights we update the parameters
        # of the distributions
        for d in range(self.comp):
            distributions[d].estimateParameters(resp[:, d])

        weight = np.mean(resp, axis=0)
        return weight

class RegimeDetection:

    def __init__(self):
        pass

class Prediction:
    def __init__(self, Data, Mean, freq=22, length=150):
        self.data = Data
        self.mean = np.exp(Mean) - 1
        self.freq = freq
        self.len = length

    def getLevels(self):
        # initiating lists to store data        
        Price=[]
        index=[]
        level=[self.data.iloc[0]]
        # calculating the price levels 
        for i in range(int(self.len/self.freq + 1)):
            Price.append(self.data.iloc[self.freq*i].values)
            index.append(self.data.iloc[self.freq*i].name)
        # level calculation
        for i in range(1, int(self.len/self.freq + 1)):
            level.append(self.data.iloc[self.freq*(i-1)].values*(self.mean+1)**self.freq)
        # Dataframe 
        Pred= pd.DataFrame(Price, columns=['Actual'])
        Pred['Date']=index
        Pred['Levels'] = level
        Pred['Levels']=Pred.Levels.apply(lambda x: x[0])
        Pred.loc[0,'Levels'] = np.nan
        Pred=Pred.set_index('Date')
        Pred['Residuals'] = (Pred.Actual-Pred.Levels)#/self.freq
        Pred.iloc[-1, [0, 2]] =np.nan
        return Pred

    def plotLevels(self, Axes=None, showActual=True):
        pred = self.getLevels()
        if (Axes==None):
            plt.figure(figsize=(18, 6))
            ax = plt.gca()
            ax.set(title='Price Level- Actual v/s Prediction')
        else:
            ax=Axes
        
        pred.Levels.plot(ax=ax, marker='o', color='b', label='Predcition')
        if (showActual):
            pred.Actual.plot(ax=ax, marker='o', color='r', label='Actual')
        ax.legend()