# -*- coding: utf-8 -*-
"""MASS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBI66pviube9O2k4mS7073OBXUhUMhvN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import random 
import matplotlib.dates as mdates
from matplotlib.patches import Rectangle
#plt.style.use('seaborn')
from scipy import stats, signal

class DistanceProfile:
    def __init__(self, Set1, Set2, threshold=0.90):
        self.set1 = Set1.values.flatten()
        self.set2 = Set2.values.flatten()
        self.len1 = len(self.set1)
        self.len2 = len(self.set2)
        self.thd = threshold 

        if self.len1 != self.len2:
            raise ValueError('Length must be same!')

        self.mean1 = np.mean(self.set1)
        self.mean2 = np.mean(self.set2)
        self.std1 = np.std(self.set1, ddof=1)
        self.std2 = np.std(self.set2, ddof=1)

    def getDistance(self):
        dist = 2* (self.len1- ((np.dot(self.set1, self.set2) - self.len1*self.mean1*self.mean2)/(self.std1*self.std2)))
        return np.sqrt(dist)
    
    def checkCorrelation(self):
        threCorr = np.sqrt(2*(self.len1 - (self.len1-1)*self.thd))
        return threCorr > self.getDistance()

class MASS:
    def __init__(self, Query, Target):
        self.q = Query
        self.h = Target
        self.m = len(self.q)
        self.n = len(self.h)
    
    def getNormalised(self):
        Q = stats.zscore(self.q, ddof=1)
        stdv = self.h.rolling(self.m).std(ddof=1).values.flatten()
        Q = np.append(Q[::-1], np.zeros(self.n-self.m))
        dots = np.convolve(self.h.values.flatten(), Q)
        dist = 2 * (self.m - (dots[self.m-1:self.n]/ stdv[self.m-1:self.n]))
        return np.sqrt(dist)


    def getNormalised_updated(self):
        
        # Q = stats.zscore(self.q, ddof=1)
        # stdv = self.h.rolling(self.m).std(ddof=1).values.flatten()
        # colName = Q.columns[0]
        # dots = np.convolve(self.h[colName], Q[colName][::-1])
        # resDf = pd.DataFrame(stdv, index = self.h.index, columns = ['STDEV'])
        # resDf = resDf.loc[self.h.index[-len(dots[(self.m-1):-(self.m-1)]):]]
        # resDf['Q'] = dots[(self.m-1):-(self.m-1)]
        # resDf['Distance'] = np.sqrt(-2*(resDf['Q'].div(resDf['STDEV']) -self.m))
        #
        # return resDf
        colName = self.q.columns[0]  # safe, since self.q is a DataFrame
        Q = pd.Series(stats.zscore(self.q[colName], ddof=1),
                      index=self.q.index,
                      name=colName)

        stdv = self.h.rolling(self.m).std(ddof=1)
        dots = np.convolve(self.h[colName].values, Q[::-1].values)

        resDf = pd.DataFrame(stdv.values.flatten(), index=self.h.index, columns=['STDEV'])
        resDf = resDf.loc[self.h.index[-len(dots[(self.m - 1):-(self.m - 1)]):]]
        resDf['Q'] = dots[(self.m - 1):-(self.m - 1)]
        resDf['Distance'] = np.sqrt(-2 * (resDf['Q'].div(resDf['STDEV']) - self.m))

        return resDf

    def getActual(self):
        sma = self.h.rolling(self.m).mean().values.flatten()
        stdv = self.h.rolling(self.m).std(ddof=1).values.flatten()
        meanq= self.q.mean().values
        stdq = self.q.std(ddof=1).values
        Q = np.append(self.q[::-1], np.zeros(self.n-self.m))
        dots = np.convolve(self.h.values.flatten(), Q)
        dist =2 * (self.m - ((dots[self.m-1:self.n]-self.m*meanq*sma[self.m-1:self.n])/ (stdq*stdv[self.m-1:self.n])))
        return np.sqrt(dist)

class Match:
    def __init__(self, Data, QueryDate, windowSize=5, lookback=True, threshold = 0.90):
        self.data = Data.loc[:QueryDate]
        self.ref = QueryDate
        self.win = windowSize
        self.look = lookback
        self.hist = self.data.loc[:self.ref]
        if self.look is False:
            self.query = self.data.loc[self.ref:][:self.win]
        else:
            self.query = self.hist[-self.win:]
        self.num=None
        self.thd = threshold
        self.thdcorr = np.sqrt(2*(self.win - (self.win-1)* self.thd))

    def getDP(self, normalize=True):
        if normalize is True:
            dp = MASS(Query=self.query, Target=self.hist).getNormalised_updated()
        else:
            dp = MASS(Query=self.query, Target=self.hist).getActual()
        return dp
    
    def getDates(self):
        dp = self.getDP()
        dp['DDiff'] = pd.to_datetime(self.ref) -dp.index
        dp.sort_values("Distance", inplace= True)
        return dp[(dp['Distance'] < self.thdcorr) & (dp['Distance'] > 1.414214) & (dp['DDiff'] > pd.Timedelta(25, "d"))]
    
    def plotDP(self, Axes=None):
        dp = self.getDP()
        if Axes is None:
            fig, ax = plt.subplots(1, figsize=(24, 6))
        else:
            ax = Axes
        ax.plot(self.hist.index[self.win-1:], dp)
        ax.axhline(self.thdcorr, color='k')

    def getMatchIndex(self):
        # dp = self.getDP()
        # idx = np.argsort(dp)#[:self.num]
        # match_idx = self.hist.iloc[idx].index
        # return idx, match_idx
        dp = self.getDP()
        # sort by Distance column
        idx = np.argsort(dp["Distance"].values)  # 1D array
        match_idx = self.hist.iloc[idx].index
        print("dp shape:", dp.shape)
        print("idx shape:", idx.shape)
        return idx, match_idx
    
    def getRegime(self):
        si, sd = self.getMatchIndex()
        dp = self.getDP()
        
        ed = self.data.iloc[si+self.win].index
        reg = pd.DataFrame([si, sd, ed, dp[si]], index=['idx', 'start', 'end', 'dp']).T
        # reg['window'] = np.repeat(self.win, self.num)
        return reg[reg['dp']< self.thdcorr]
    
    def getDPValues(self):
        dp = self.getDP()
        if self.num is None:
            self.num=self.getRegime().shape[0]
        idx = self.getMatchIndex()[0]
        return dp[idx]

    def plotMatch(self, Axes=None):
        # setting up the axes
        if Axes is None:
            fig, ax = plt.subplots(1, figsize=(24, 6))
        else:
            ax = Axes
               
        reg = self.getRegime().idx
        for i in range(len(reg)):
            zNorm = stats.zscore(self.hist.values[reg[i]: reg[i]+self.win])
            ax.plot(zNorm, lw=2)

    def plotTS(self, Axes = None, plot_hist=True):
        # setting up the axes
        if Axes is None:
            fig, ax = plt.subplots(1, figsize=(24, 6))
        else:
            ax = Axes
        reg = self.getRegime().idx
        date = self.getRegime().start
        if plot_hist is True:
            self.hist.plot(ax=ax, alpha=0.2, color='b')
        for i in range(len(reg)):
            ax.plot(self.hist[reg[i]: reg[i]+self.win], color='g')
        self.query.plot(ax=ax, color='r')

class SignalAnalysis:
    def __init__(self, Data, QueryDate, RegIndex=None, windowSize=5, lookback=True, threshold = 0.90):
        self.data = Data
        self.ret = np.log(self.data)-np.log(self.data.shift())
        self.ref = QueryDate
        self.index = RegIndex
        self.win = windowSize
        self.look = lookback
        self.thd = threshold
        self.em20 = self.data.ewm(span = 20, adjust=False).mean()[20:]
        self.em200 = self.data.ewm(span = 200, adjust=False).mean()[200:]
        self.emt = (self.em20-self.em200)[200-20:]
        self.vol = self.ret[1:].rolling(65).std(ddof=1)[65:]
        self.mass = Match(self.data, self.ref, windowSize=self.win, lookback=self.look , threshold = self.thd)
        self.ext = None
    
    def getEMTable(self):
        reg = self.mass.getRegime().iloc[self.index]
        sd= reg['start'].values
        ed= reg['end'].values
        reg['startEM']=self.emt.loc[sd].values
        reg['endEM']=self.emt.loc[ed].values
        reg['changeEM']= (reg.endEM - reg.startEM)/ np.abs(reg.startEM)
        reg['avgEM']= [self.emt.loc[sd[i]:ed[i]].values.mean() for i in range(reg.shape[0])]
        reg['RevertingEM']= [0 if (reg.endEM.iloc[i]-reg.avgEM.iloc[i])/(reg.avgEM.iloc[i]-reg.startEM.iloc[i])>0 else 1 for i in range(reg.shape[0])]
        return reg

    def getVolTable(self):
        reg = self.mass.getRegime().iloc[self.index]
        sd= reg['start'].values
        ed= reg['end'].values
        reg['startVol']=self.vol.loc[sd].values
        reg['endVol']=self.vol.loc[ed].values
        reg['changeVol']= (reg.endVol - reg.startVol)/ np.abs(reg.startVol)
        reg['avgVol']= [self.vol.loc[sd[i]:ed[i]].values.mean() for i in range(reg.shape[0])]
        reg['RevertingVol']= [0 if (reg.endVol.iloc[i]-reg.avgVol.iloc[i])/(reg.avgVol.iloc[i]-reg.startVol.iloc[i])>0 else 1 for i in range(reg.shape[0])]
        return reg

    def getGenTable(self, ExternalData):
        self.ext = ExternalData
        reg = self.mass.getRegime().iloc[self.index]
        sd= reg['start'].values
        ed= reg['end'].values
        reg['startExt']=self.ext.loc[sd].values
        reg['endExt']=self.ext.loc[ed].values
        reg['changeExt']= (reg.endExt - reg.startExt)/ np.abs(reg.startExt)
        reg['avgExt']= [self.ext.loc[sd[i]:ed[i]].values.mean() for i in range(reg.shape[0])]
        reg['RevertingExt']= [0 if (reg.endExt.iloc[i]-reg.avgExt.iloc[i])/(reg.avgExt.iloc[i]-reg.startExt.iloc[i])>0 else 1 for i in range(reg.shape[0])]
        return reg
    
    def getCombined(self):
        df1 = self.getEMTable()
        df2 = self.getVolTable()
        return pd.merge(df1, df2, on=['idx', 'start', 'end', 'dp'], how='outer')
    
    def combineExt(self, df, df_ext):
        return pd.merge(df, df_ext, on=['idx', 'start', 'end', 'dp'], how='outer')



# class SimiliarityCheck:
#     def __init__(self, Data, QueryDate, maxWindow=10, numMatch=3, windowSize=5):
#         self.data = Data
#         self.ref = QueryDate
#         self.win = windowSize
#         self.mwin = maxWindow
#         self.num = numMatch

#     def getRegimes(self):
#         reg = []
#         for i in range(1, self.mwin+1):
#             reg.append(Match(self.data, self.ref, windowSize=i*self.win).getRegime())
#         ind = range(1, self.mwin+1)
#         return pd.DataFrame(reg, index=ind)

#     def bestMatch(self):
#         s= self.getRegimes()
#         # top 5 mathces
#         dates= pd.DataFrame(np.unique(s.values.flatten(), return_counts=True)).T.sort_values(1)[::-1].head()
#         return dates[0].values