# -*- coding: utf-8 -*-
"""TSA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LOeSfQZVm9cpwe0Vi_Nb0N-wJgC_WoD4

[Documentation](https://docs.google.com/document/d/1U9FHt_I8pU6zogpfww8QI-2Xwb_yAzEE3mfmn7_x2D0/edit?usp=sharing)

## Importing Libraries
"""

# Basic Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns

# plt.style.use('seaborn')

# External Libraries
from scipy.signal import dimpulse 
import scipy.linalg as la
import scipy.stats as st
# import statsmodels.api as sm
import scipy.optimize as opt
from copy import deepcopy
import datetime
from statsmodels.stats.diagnostic import acorr_ljungbox

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Checking purpose
from statsmodels.tsa.stattools import acf, pacf, adfuller

class Preprocess:
    
    def __init__(self, Data, ticker=None, start=None, end=None, freq=None, days = None, fillMethod='bfill'):
        self.data = Data
        self.ticker = ticker
        self.start = start
        self.end = end
        self.freq = freq
        self.fill = fillMethod
        self.days = days 
    
    def getProcessedData(self):
        # Localise Variables
        df = self.data
        if self.freq is not None:
            # change frequency if specified
            df = df.asfreq(self.freq)
            # fill nan values 
            df = df.fillna(method=self.fill)

        if self.days is not None:
            df = df.iloc[df.index.get_loc(self.start)-self.days: df.index.get_loc(self.start)]

        if (self.ticker is None):
            return df.loc[self.start:self.end]
        else:
            # specific columns only
            return df.loc[self.start:self.end, self.ticker]
        return df

class Returns:

    def __init__(self, Data):
        self.data = Data
    
    def getDecimal(self):
        # Localise 
        df = self.data
        # Calculate and discard first obs
        df=df.pct_change()[1:]
        return df
    
    def getValue(self):
        # Localise Variable
        ret = self.getDecimal()
        # Conversion
        ret = ret.apply(lambda x: x+1)
        return ret

    def getLogReturns(self):
        # Localise variable
        val = self.getValue() 
        # Log transformation
        val = val.apply(lambda x : np.log(x)) 
        return val
      
    def getGrossHPR(self):
        # localise Variable
        logR = self.getLogReturns()
        # total value
        total = logR.sum()
        return total
    
    def getNetHPR(self):
        # localise Variable
        gross = self.getGrossHPR()
        # net value
        net = np.exp(gross)-1
        return net

class Smooth:

    def __init__(self, Data, lookback=20):
        self.data = Data
        self.span = lookback

    def getRollWMA(self, window='hanning'):
        # Localise Variable
        data = self.data
        # Rolling window Mean
        winAvg = data.rolling(self.span, min_periods=self.span, center=True, win_type=window).mean()
        return winAvg

    def getSMA(self):
        # Loacalise Variable
        data = self.data
        # Simple Moving Average
        SMA = data.rolling(self.span, min_periods=self.span).mean()
        return SMA

    def getEMA(self):
        # Localise Variable
        data = self.data       
        # Exponential Moving averages
        EMA = data.ewm(span = self.span, adjust=False).mean()
        return EMA

class Test:

    def __init__(self, Data, confidence=0.95):
        self.data = Data.values.flatten()
        self.alpha = 1- confidence

    def DickeyFuller(self):
        stats = adfuller(self.data)
        return stats[:2]

    def JarqueBera(self):
        stats = st.jarque_bera(self.data)
        return stats

    def LjungBox(self, lags=None):
        stats = acorr_ljungbox(self.data, lags = lags, return_df=True)
        stats['SAC'] = stats['lb_pvalue'] < self.alpha
        return stats

    def checkStationarity(self):
        stats = self.DickeyFuller()
        return stats[1] < self.alpha

    def checkNormality(self):
        stats = self.JarqueBera()
        return stats[1] > self.alpha

class DeTrend:

    def __init__(self, Data, lookback=20, typeAdd=True):
        self.data = Data
        self.len = len(Data)
        self.span = lookback
        # type of decomposition
        if (typeAdd):
            self.add = True
        else:
            self.mul = True
    
    def getPolyfit(self, degree=2):
        # getting Value
        df = self.data.copy()
        lback = self.span
        # spliting 
        X = np.arange(self.len).reshape(-1, 1)
        y = df.values.reshape(-1, 1)
        # polynomial processing
        poly = PolynomialFeatures(degree)
        X_poly=poly.fit_transform(X)
        # fitting linear reg
        model = LinearRegression().fit(X_poly, y)
        # predicting trend
        trend = model.predict(X_poly).flatten()
        #detrending
        if (self.add):
            detrend = df.values-trend
        elif (self.mul):
            detrend = df.values/trend
        # dataframe
        data = pd.DataFrame(df)
        data['Trend'] = trend
        data['Detrend'] = detrend
        return data

    def getEMAfit(self):
        # getting Value
        df = self.data
        lback = self.span
        # smoothing to get trend
        EMtrend = Smooth(df, lookback=lback).getEMA()
        # detrending
        if (self.add):
            detrend = df-EMtrend
        elif (self.mul):
            detrend = df/EMtrend
        # dataframe
        data = pd.DataFrame(df)
        data['Trend'] = EMtrend.values
        data['Detrend'] = detrend.values
        return data

    def getSMAfit(self):
        # getting Value
        df = self.data
        lback = self.span
        # smoothing to get trend
        SMtrend = Smooth(df, lookback=lback).getSMA()
        #detrending
        if (self.add):
            detrend = df-SMtrend
        elif (self.mul):
            detrend = df/SMtrend
        # dataframe
        data = pd.DataFrame(df)
        data['Trend'] = SMtrend.values
        data['Detrend'] = detrend.values
        return data

class FractionalDifferencing:

    def __init__(self, numLag=14, fraction=0.5, tolerance=1e-4):
        self.lag = numLag
        self.frac = fraction
        self.tol = tolerance

    def convergence(self, arr):
        for i in range(1, len(arr)-1):
            tol = (arr[i+1]-arr[i])
            if np.abs(tol) <= self.tol:
                # print('convergence')
                break       
        return i+1, arr[i]

    def getWeights(self):
        # initialise the weight 
        w=[1]
        wdiff = []
        # assigning weights
        for k in range(1, self.lag+2):
            # calculate weights using binamial theorem
            weight = -w[k-1]*((self.frac-k+1))/k
            # append to the list of weights to use it further
            w.append(weight)
        # reshape the weight matrix
        idx = self.convergence(w)[0]
        if self.lag > idx : 
            self.lag = idx
        w = np.asarray(w).reshape(-1,1) 
        return w[: self.lag]

    def getDifferencedSeries(self, Data):
        # getting values
        w = self.getWeights()
        # initialise results
        x=Data.values
        series =[]
        for i in range(self.lag, len(x)):
            ser=0
            for k in range(self.lag):
                ser+= x[i-k]*w[k]
            series.append(ser[0])
        df = pd.DataFrame(series)
        return df

class FractionEstimate:
    def __init__(self, Data, numLag= 14, interval=0.1, confidence=0.95, tolerance=1e-2):
        self.data = Data
        self.lag = numLag 
        # array of the fractions
        self.frac = np.arange(1, 0, -interval)
        self.alpha = confidence
        self.tol = tolerance

    def getEstimate(self):
        # initialise a list
        fractions = []
        for i, frac in enumerate(self.frac):
            # temp array for fractional differencing series
            temp = FractionalDifferencing(self.lag, fraction=frac, tolerance=self.tol).getDifferencedSeries(self.data)
            # testing for stationary
            test = Test(temp, confidence=self.alpha).checkStationarity()
            fractions.append([i, round(frac, 2),  test])
        # store in dataframe
        df = pd.DataFrame(fractions, columns=['Index', 'Fraction', 'Stationary'])
        return df.set_index('Index')

    def getBest(self):
        # getting smallest fraction for which it can be stationary
        x = self.getEstimate()
        if x['Stationary'].sum() !=0:
            f = x[x.loc[:, 'Stationary'] == True].iloc[-1, 0]
        else: 
            f = 1
        return f

class BackOperation:
    def __init__(self, Actual, DiffSeries, numLag=14, fraction=0.5, tolerance=1e-4):
        self.data = DiffSeries
        self.act = np.log(Actual)
        self.lag = numLag
        self.init = self.act[:self.lag]
        
        self.len = len(self.data)
        self.frac = fraction
        self.tol = tolerance
        self.weights = FractionalDifferencing(self.lag, fraction=self.frac, tolerance = self.tol).getWeights()[1:]
        
    def getPrediction(self):
        # Need the array uptill 2*lag
        prices = list(self.init)
        # starting from self.lag:2*self.lag and so on to predict 28th observation
        for i in range(1, self.len+1):
            price = self.data[i-1]
            price -= np.sum(prices[i : i + self.lag-1] * self.weights.flatten()[::-1])
            prices.append(price)
        return pd.DataFrame(np.exp(prices))
    
    def plot(self, Axes=None):
        price = self.getPrediction()
        if Axes is None:
            plt.figure(figsize=(24,8))
            ax = plt.gca(title='Actual vs Predicted Price')
        else:
            ax = Axes
        ax.plot(self.act.index, np.exp(self.act.values), label='Actual', color='r', alpha =0.8)
        ax.plot(self.act.index, price.values, label='Predicted', marker = 'o', color='k', alpha =0.8)
        ax.legend()

class ConfidenceInterval:

    def __init__(self, Data, confidence=0.95):
        self.data = Data
        self.len = len(Data)
        self.alpha = 1-confidence

    def getCI(self):
        # Mean
        mean = np.mean(self.data)
        # Standard Error
        SE = st.sem(self.data)
        # inverse t-distribution at 95% CI
        lo = self.alpha/2
        up = 1 - lo 
        # Bounds
        UpBound = st.t.ppf(up, len(self.data)-1, loc=mean, scale = SE)
        LoBound = st.t.ppf(lo, len(self.data)-1, loc=mean, scale = SE)

        # Output
        CI = pd.DataFrame([[mean, UpBound, LoBound]], columns=['Mean', 'Up', 'Lo'] )
        return CI

    def getNormCI(self):
        # Mean
        mean = np.mean(self.data)
        # Standard Error
        SE = st.sem(self.data)
        # inverse norm-distribution at 95% CI
        lo = self.alpha/2
        up = 1 - lo 
        # Bounds
        UpBound = st.norm.ppf(up, loc=mean, scale = SE)
        LoBound = st.norm.ppf(lo, loc=mean, scale = SE)

        # Output
        CI = pd.DataFrame([[mean, UpBound, LoBound]], columns=['Mean', 'Up', 'Lo'] )
        return CI

class LagOperator:

    def __init__(self, posCoef=None, negCoef=None):
        # Corresponds to 1+theta+....
        self.poslag = posCoef
        # Corresponds to 1-phi-...........
        self.neglag = negCoef
        
    def getPosComp(self):
        if (self.poslag is None):
            # No lag 
            theta = np.array([1])
        else:
            # There is some Lag Component
            theta = np.asarray(self.poslag)

            # Insert 1 at the begining of array
            theta = np.insert(theta, 0, 1)
    
        return theta  

    def getNegComp(self):
        if (self.neglag is None):
            # No lag 
            phi = np.array([1])

        elif (np.isscalar(self.neglag)):
            # Single lag
            phi = np.array(-self.neglag)
        
        else:
            # Many lags
            phi = -np.asarray(self.neglag)
        
        # Insert 1 at begining of the array
        phi = np.insert(phi, 0, 1)

        return phi

class Periodogram:

    def __init__(self, Data, confidence=0.95):
        self.data = Data
        self.alpha = confidence
        # length of time series
        self.length = len(self.data)

    def getSpectEst(self):
        dp = self.data
        n = self.length
        
        # Discrete Fourier Transform to datapoints
        transdata = np.fft.fft(dp)

        estimate = np.abs(transdata)**2 / n 
        estimate[0] = 0
        # Array Discrete Fourier frequencies    
        frFreq= 2 * np.pi * np.arange(n) / n  
        
        SpectEst= pd.Series(estimate, index = frFreq, name = 'Spectral Estimate')

        return SpectEst

    def plot(self, Axes=None):
        # getting values
        SpectEst = self.getSpectEst()
        n = len(SpectEst)
        CI = ConfidenceInterval(SpectEst, confidence=self.alpha).getCI()
        Up = CI.iloc[:, 1].values
        Lo = CI.iloc[:, 2].values

        if (Axes==None):
            # Setting up the Axes
            plt.figure(figsize=(12,6))
            ax = plt.gca()
            ax.set(title='Periodogram', xlabel='frequency', ylabel='spectrum')
        else:
            # Get the Axes
            ax = Axes
        # plots line chart
        ax.plot(SpectEst)
        ax.axhline(Up, xmin=0, xmax=n-1, color='r', linestyle='--')
        ax.axhline(Lo, xmin=0, xmax=n-1, color='r', linestyle='--')

class AutoCovariance:

    def __init__(self, Data, numLag=40, confidence=0.95):
        self.ts = Data
        self.alpha = confidence
        self.spect = Periodogram(self.ts).getSpectEst()
        self.lag = numLag

    def getbySpectEst(self):
        # Localise variable
        klag = self.lag

        # Calculating the real part of spectral estimate 
        acov = np.fft.ifft(self.spect).real
        
        AutoCov = pd.Series(acov[:klag],index=list(range(klag)), name='AutoCovariance')

        return AutoCov

class AutoCorrelation:

    def __init__(self, Data, numLag=40, confidence=0.95):
        self.ts = Data
        self.lag = numLag
        self.alpha = confidence

        self.autocov = AutoCovariance(self.ts, numLag=self.lag).getbySpectEst()
        self.var = self.autocov[0]
        
    def getbySpectEst(self):
        # getting values
        AutoCov = self.autocov
        Var = self.var
        # calculating correlation
        acor = AutoCov / Var
        return acor

    def getStandard(self):
        # getting values
        klag = self.lag
        TsData = self.ts
        # Series Transformation
        AutoCor= pd.Series(acf(TsData, nlags=klag-1),index=list(range(klag)), name='AutoCorrelation')

        return AutoCor
  
    def plot(self, Axes=None):
        # getting values
        klag = self.lag
        acor = self.getbySpectEst()
        # Calculating confidence intervals
        CI = ConfidenceInterval(acor, confidence=self.alpha).getNormCI()
        Up = CI.iloc[:, 1].values
        Lo = CI.iloc[:, 2].values

        if (Axes==None):
            # Setting up the Axes
            plt.figure(figsize=(12,6))
            ax = plt.gca()
            ax.set(title='ACF',
                    xlabel='lag', ylabel='Correlation')
        else:
            # Get the Axes
            ax = Axes

        # plots stem filter
        ax.stem(acor)
        ax.axhline(Up, xmin=0, xmax=klag-1, color='r', linestyle='--')
        ax.axhline(Lo, xmin=0, xmax=klag-1, color='r', linestyle='--')

class PartialAutoCorrelation:

    def __init__(self, Data, numLag=40, confidence=0.95):
        self.ts = Data
        self.lag = numLag
        self.alpha = confidence

    def getStandard(self):
        # getting values
        klag = self.lag
        TsData = self.ts
        # Series Transformation
        PAutoCorr = pd.Series(pacf(TsData, nlags=klag-1, method='yw'), index=list(range(klag)), 
                              name='Partial AutoCorrelation' )
        return PAutoCorr

    def plot(self, Axes=None):
        # getting data
        klag = self.lag
        PAutoCorr= self.getStandard()
        # calculate confidence interval 
        CI = ConfidenceInterval(PAutoCorr, confidence=self.alpha).getNormCI()
        Up = CI.iloc[:, 1].values
        Lo = CI.iloc[:, 2].values

        if (Axes==None):
            # Setting up the Axes
            plt.figure(figsize=(12,6))
            ax = plt.gca()
            ax.set(title='Partial AutoCorrelation',
                   xlabel='lag', ylabel='partial autocorrelation')
        else:
            # Get the Axes
            ax = Axes

        # plots stem filter
        ax.stem(PAutoCorr)
        ax.axhline(Up, xmin=0, xmax=klag-1, color='r', linestyle='--')
        ax.axhline(Lo, xmin=0, xmax=klag-1, color='r', linestyle='--')

class SizeEqualiser:

    def __init__(self, Small, Large):
        self.large = Large
        self.small = Small
        self.lsize = len(self.large)
        self.ssize = len(self.small)
        
        if (self.ssize > self.lsize):
            raise ValueError("Reverse Input order")
    
    def checkSize(self):
        if (self.lsize == self.ssize):
            # same size
            print('Sizes are same!!')
        
        return self.lsize == self.ssize

    def matchSize(self):
        # Loacalize Variable
        large = self.large
        small = self.small

        if self.checkSize() is False:
            # In case of different size
            temp = np.zeros(len(large)-len(small))
            small = np.hstack((small, temp))

        return small, large

class ImpulseResponse:
    
    def __init__(self, ResComp, FuncComp, timeStep=1, impLen = None):
        # Equalise size of array
        if (len(ResComp)> len(FuncComp)):
            self.phi, self.theta = SizeEqualiser(FuncComp, ResComp).matchSize()
        elif (len(ResComp)< len(FuncComp)):
            self.theta, self.phi = SizeEqualiser(ResComp, FuncComp).matchSize()
        else:
            self.theta = ResComp
            self.phi = FuncComp

        self.len = impLen
        self.t = timeStep

    def getSystemInstance(self):
        # Localise Variable
        Res = self.theta
        Func = self.phi

        # (Num, Den, steps)
        SysIns = Res, Func, self.t
        return SysIns
 
    def getImpRes(self): 
        # get system instance
        SysIns = self.getSystemInstance()
        len = self.len
        # Conversion into impulse response
        time, impulse = dimpulse(SysIns, n=len)
        # result array
        impulse = impulse[0].flatten()

        ImpResponse = pd.Series(impulse, index = time, name = 'Impulse Response')

        return ImpResponse

    def plot(self, Axes=None):
        # getting values
        ImpResponse = self.getImpRes()

        if (Axes==None):
            # Setting up the Axes
            plt.figure(figsize=(12,6))
            ax = plt.gca()
            ax.set(title='Impulse response', xlabel='time', ylabel='response')
        else:
            # Get the Axes
            ax = Axes
        # plots stem chart
        ax.stem(ImpResponse)

class DeSeason:
    
    def __init__(self, Data, period, typeAdd=True):
        self.df = Data
        self.period = period
        # type of decomposition
        if (typeAdd):
            self.add = True
        else:
            self.mul = True

    def getNoise(self):
        # getting values 
        df = self.df
        period = self.period
        # deseasoning 
        if (self.add):
            deseason = df - df.shift(period)
        elif (self.mul):
            deseason = df / df.shift(period)
        # getting noise   
        noise = deseason[period:]
        return noise
    
    def getSeasonComp(self):
        pass

class Decompose:
    
    def __init__(self):
        pass
    
    def getSTL(self):
        pass

    def getSD(self):
        pass

class Period:

    def __init__(self, Data, confidence = 0.95):
        self.data = Data
        self.len = len(self.data)
        self.alpha = confidence


    def getPeriod(self):
        # Estimate Spectral Density
        sd = Periodogram(self.data, confidence = self.alpha).getSpectEst()
        # seasonal frequency
        Freq = sd.idxmax()
        # period
        # period = 2 * np.pi / Freq
        numPeriod = self.len/Freq
        return numPeriod

class TSA:
    def __init__(self, Data, lags=40, confidence = 0.95):
        self.data = Data
        self.values = self.data.values.flatten()
        self.lag = lags
        self.conf = confidence

    def plot(self):
        # settiing up the axes
        plt.figure(figsize=(18,12))
        layout = (3,2)
        ts_ax = plt.subplot2grid(layout, (0, 0), colspan=2)
        acf_ax = plt.subplot2grid(layout, (1, 0))
        pacf_ax = plt.subplot2grid(layout, (1, 1))
        qq_ax = plt.subplot2grid(layout, (2, 0))
        pp_ax = plt.subplot2grid(layout, (2, 1))
        # plotting the time series
        self.data.plot(ax=ts_ax)
        ts_ax.set(title="Time Series")

        # ACF and PACF
        AutoCorrelation(self.values, numLag=self.lag, confidence = self.conf).plot(Axes=acf_ax)
        acf_ax.set_title('Autocorrelation')
        PartialAutoCorrelation(self.values, numLag=self.lag, confidence = self.conf).plot(Axes=pacf_ax)
        pacf_ax.set_title('PartialAutocorrelation')
        # qq and prob plot
        # sm.qqplot(self.values, line='s', ax=qq_ax)
        # qq_ax.set_title('QQ Plot')        
        st.probplot(self.values, sparams=(self.data.mean(), self.data.std()), plot=pp_ax)
        pp_ax.set_title('Probability Plot') 

        plt.tight_layout()

class Weekly:
    def __init__(self, Data):
        self.data = Data.copy()

    def getTransformedData(self):
        self.data['Week'] = self.data.index.isocalendar().week
        wConSr = pd.Series(index = self.data.index, dtype = 'float64')
        wConSr.loc[self.data.index[0]] = 1

        for i in self.data.index[1:]:

            ind = self.data.index.get_loc(i)
            wDiff = int(self.data.iloc[ind]['Week']) - int(self.data.iloc[ind-1]['Week'])

            indWcon = wConSr.index.get_loc(i)

            if wDiff ==0 :
                wConSr.loc[i] = wConSr.iloc[indWcon-1]
            else:
                wConSr.loc[i] = wConSr.iloc[indWcon-1] + 1
                
        self.data['Week_Con'] = wConSr
        weekEndSr = self.data.groupby('Week_Con').tail(1)
        df_weekly = pd.DataFrame(index = weekEndSr.index)
        df_weekly['Close'] = weekEndSr['N50']
        # df_weekly['PClose'] = df_weekly['Close'].shift()
        return df_weekly

class Probability:
    def __init__(self, simData, freqLevel = 5):
        self.data = simData
        self.sim = self.data.shape[0]
        self.rep = self.data.shape[1]
        self.freq = freqLevel 

    def getChunks(self):
        chunks = []
        for i in range(int(np.ceil(self.sim/self.freq))):
            chunks.append(self.data.iloc[self.freq*i: self.freq*(i+1), :])
        return chunks
    
    def getLevels(self):
        levels = []
        chunks = self.getChunks()
        for i in range(len(chunks)):
            sims = chunks[i].values.flatten()
            median = np.quantile(sims, q=0.5)
            q25 = np.quantile(sims, q=0.25)
            q75 = np.quantile(sims, q=0.75)
            q95 = np.quantile(sims, q=0.95)
            q5 = np.quantile(sims, q=0.05)
            levels.append(np.array([q5, q25, median, q75, q95]))
        return levels
    
    def getPredInstances(self):
        ins = []
        chunks = self.getChunks()
        levels = self.getLevels()
        for i in range(len(chunks)):
            lookup = chunks[i].iloc[-1, :].values
            zone = []
            for j in range(len(lookup)):
                if (lookup[j] <= levels[i][0]) or (lookup[j] > levels[i][-1]): 
                    zone.append(-1)
                elif (lookup[j] <= levels[i][1]) and (lookup[j]> levels[i][0]):
                    zone.append(1) 
                elif (lookup[j] <= levels[i][2]) and (lookup[j]> levels[i][1]):
                    zone.append(2)
                elif (lookup[j] <= levels[i][3]) and (lookup[j]> levels[i][2]):
                    zone.append(3)
                elif (lookup[j] <= levels[i][4]) and (lookup[j]> levels[i][3]):
                    zone.append(4)
                else:
                    zone.append(0)

            IZ = pd.DataFrame({})
            IZ['Instance'] = lookup
            IZ['Zone'] = zone
            ins.append(IZ)
        return ins

    def getProbability(self):
        IZ = self.getPredInstances()
        prob = []
        for i in range(len(IZ)):
            prob.append((IZ[i].groupby('Zone').count()/self.rep))
        # pd.DataFrame()
        return prob


    def plot(self, Axes=None):
        levels = self.getLevels()
        if Axes is None:
            fig, ax =plt.subplots(figsize=(24, 6))
        else:
            ax=Axes
        ax.set_xlim(0, self.freq*int(np.ceil(self.sim/self.freq)))
        self.data.plot(ax=ax, color='r', alpha=0.3)
        for j in range(len(levels)):
            for i in range(5):
                ax.axhline(levels[j][i], xmin=(j/len(levels)), xmax=((j+1)/len(levels)), color='b', alpha=0.5)
        ax.get_legend().remove()